/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.simplyapped.playground;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Antlr classUnderTest = new Antlr();
    }
}
